### ISSUE TITLE
modem.bin is not found

### ISSUE THREAD

**Issue by eurol** [fr0ster/buildroot-OrangePI-2G-IOT#1]
File buildroot-devel/board/orangepi/orangepi-2g-iot/post-build.sh:

line:
cp /tmp/OrangePiRDA_external/bootarg/modem.bin $BINARIES_DIR

change to:
cp /tmp/OrangePiRDA_external/chips/RDA/bootarg/modem.bin $BINARIES_DIR

Thanks to https://4pda.to/forum/index.php?showtopic=813602&view=findpost&p=115327991
Now builds ok.

**Comment by fr0ster** [comment]
Thanks, add new commit
